apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-web-hello-deployment
spec:
  selector:
    matchLabels:
      app: k8s-web-hello
  replicas: 5
  template:
    metadata:
      labels:
        app: k8s-web-hello
    spec:
      containers:
      - name: web-app
        image: raghumn/k8s-web-hello
        ports:
        - containerPort: 3000


