apiVersion: v1
kind: Service
metadata:
  name: k8s-web-to-nginx-service
spec:
  type: NodePort
  selector:
    app: k8s-web-to-nginx
  ports:
  - port: 31000
    targetPort: 3000
    nodePort: 31500
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-web-to-nginx-deployment
spec:
  selector:
    matchLabels:
      app: k8s-web-to-nginx
  replicas: 3
  template:
    metadata:
      labels:
        app: k8s-web-to-nginx
    spec:
      containers:
      - name: web-app
        image: raghumn/k8s-web-to-nginx
        ports:
        - containerPort: 3000
