apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
 selector:
   matchLabels: 
     app: nginx
 template:
   metadata:
     name: nginx-pod
     labels: 
       app: nginx
   spec:
     initContainers:
     - name: nginx-init-container
       image: nginx
       imagePullPolicy: IfNotPresent
       command: [ "/bin/bash","-c","ls /etc" ]  
     containers:
     - name: nginx-container
       image: nginx
       imagePullPolicy: IfNotPresent
 replicas: 3
