apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-statefulset
spec:
  serviceName: nginx-service
  selector:
    matchLabels:
      app: nginx
  template: 
    metadata:
      name: nginx-pod
      namespace: default
      labels: 
        app: nginx
    spec:
      containers:
      - name: nginx-c1
        image: nginx
        imagePullPolicy: IfNotPresent      
  replicas: 4
---

apiVersion: v1
kind: Service
metadata: 
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
  - port: 31492
    targetPort: 80
    name: nginxport
    nodePort: 31360
  type: NodePort

